### ISSUE TITLE
Need more information about oAuth2

### ISSUE THREAD

**Issue by lpylpyleo** [supabase/gotrue-dart#18] opened 2021-06-10 04:34 UTC
In the readme:

- signIn with oauth2 provider only return provider url. Users have to launch that url to continue the auth flow. I recommend to use url_launcher package.
- After receiving callback uri from oauth2 provider, use getSessionFromUrl to parse session data.

But I want to know how to get the callback uri from oauth2 provider? 

The example code doesn't help much:

```dart
  void _onSignInWithGithub(BuildContext context) async {
    final response = await gotrueClient.signIn(provider: Provider.github);
    if (await canLaunch(response.url)) {
      print('response.url: ${response.url}');
      await launch(response.url);
    } else {
      throw 'Could not launch ${response.url}';
    }
  }  
```

**Comment by lokesh-coder** [comment] 2021-06-10 20:00
Facing same issue. Temporarily I am using `flutter_web_auth` package for custom inline chrome tab.

```dart
import 'package:flutter_web_auth/flutter_web_auth.dart';

void signInWithGoogle() async {
    final url = Uri.https('DOMAIN', '/auth/v1/authorize', {
      'provider': 'google',
      'redirect_to': "myapp://callback",
    });

    final String callbackUri = await FlutterWebAuth.authenticate(
        url: url.toString(), callbackUrlScheme: "myapp");

    final session =
        await gotrueClient.getSessionFromUrl(Uri.parse(callbackUrl));

    print("User email => ${session.data?.user?.email}");
  }
}
```

Redirect url `myapp://callback` should be added in either **URI_ALLOW_LIST** or **Additional Redirect URLs** in supabase Auth settings.


In `android/app/src/main/AndroidManifest.xml`, I added the schema for closing the tab and returning to app,
```xml
<activity android:name="com.linusu.flutter_web_auth.CallbackActivity" >
    <intent-filter android:label="flutter_web_auth"  android:autoVerify="true">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:scheme="myapp" />
    </intent-filter>
</activity>
```

**Comment by lpylpyleo** [comment] 2021-06-11 01:54
@lokesh-coder Thanks for your solution! 
From your idea, I think we can also use deep links on Android and universal links on iOS with [uni_links](https://pub.dev/packages/uni_links) package to capture the callback url. I will have a try.

**Comment by matevarga** [comment] 2021-06-14 20:40
@lokesh-coder thanks for that -- however, how would this work for web apps (where the callback scheme and base url can vary)? Any ideas?

**Comment by lokesh-coder** [comment] 2021-06-15 15:42
@matevarga I haven't checked on web app, but custom callback scheme is only needed for mobile. For web apps, we can directly call the authorize url, like
```html
<a href="https://<domain>/auth/v1/authorize?provider=google&redirect_url=https://callback_url">Login with Google</a>
```
This will go to OAuth2 consent page and once signed in, it will redirect to callback url with necessary oauth details in callback url query params. like, 

```html
https://callback_url?access_token=abc&refresh_token=xyz&type=bearer&...
```
Generally this callback url will be you app url. You can get the access token from query params and store it in cookie or localStorage and pass it as Authorization header in all calls.

**Comment by matevarga** [comment] 2021-06-15 18:11
@lokesh-coder yep, thanks -- calling the auth endpoint is okay, the issue is that the callback must be caught so some extra hacking is needed in the dart/flutter app so that it can listen for callbacks. (it's not _that_ trivial)

**Comment by matevarga** [comment] 2021-06-19 16:46
So I got this working with some hacks -- I don't think this should be the way but leaving a comment here just in case someone needs it.
Goal:  to acquire a `GoTrue Session` after using Google Auth through Supabase in a Flutter Web app.
Problem: we need to launch an OAuth2 login screen, then catch the callback, extract the parameters.

Tools:
- url_launcher
- auto_router

Flow:
1. User initiates login by e.g. pressing a button
2. Google OAuth login is initiated
3. App receives a callback with access_token, etc.
4. These tokens are parsed and used to create a GoTrue session

What proved to be a bit tricky to me (I'm a Flutter novice): 3 and 4.

In order to receive a callback:
- create a new widget, let's call it AuthPage
```
class AuthPage extends StatelessWidget {
  final String? accesstoken;
  final String? refreshtoken;
  final String? tokentype;
  final int? expiresin;
  final String? providertoken;
  final String? errordescription;

  AuthPage(
      {@QueryParam('access_token') this.accesstoken,
      @QueryParam('refresh_token') this.refreshtoken,
      @QueryParam('expires_in') this.expiresin,
      @QueryParam('token_type') this.tokentype,
      @QueryParam('provider_token') this.providertoken,
      @QueryParam('error_description') this.errordescription});
// other code follows
```
This will enable the AutoRouter to pass the callback parameters to the widget.


- set up a new AutoRoute:
```
@MaterialAutoRouter(
  routes: [
    AutoRoute(page: AuthPage, path: "/auth")
// [.. etc ..]
```

- put a new HTML file into the `web` folder, e.g. `callback.html`
```
<html>
    <body>
    </body>
    <script>
        var url = window.location.href
        var arr = url.split("/");
        var currentUrl = arr[0] + "//" + arr[2]
        let newUrl = currentUrl + "/#/auth?" + window.location.href.substring((window.location.origin+window.location.pathname).length+1);
        window.location.href = newUrl;
    </script>
</html>
```
This HTML will strip out the required query params and forward it to the `/auth` route (i.e. to the `AuthPage` widget).

In the `build` method of `AuthPage`, add a callback to go to some kind of service/etc. that can then use the tokens to create a GoTrue session.

```  
@override
  Widget build(BuildContext context) {
    WidgetsBinding.instance?.addPostFrameCallback((timeStamp) {
      some_underlying_service.handleAuthCallback(accesstoken, refreshtoken,
            tokentype, expiresin, providertoken, errordescription);
      }
    });
```

**Comment by phamhieu** [comment] 2021-07-18 01:29
We released a new flutter package to support Supabase 3rd party deeplink authentication: https://pub.dev/packages/supabase_flutter

You can take a look at the example [here](https://github.com/phamhieu/supabase-flutter-demo) for reference.

**Closed by phamhieu** 2021-07-18 01:29 UTC
Labels: documentation

**Comment by matevarga** [comment] 2021-08-19 10:05
> We released a new flutter package to support Supabase 3rd party deeplink authentication: https://pub.dev/packages/supabase_flutter
> 
> You can take a look at the example [here](https://github.com/phamhieu/supabase-flutter-demo) for reference.

It's not clear to me (yet) how the changes solve the existing problems. I'm deciphering the example but the documentation clearly lacks the explanation about how the callback URL is parsed -- the problem has never been that it's difficult to open the provider-specific login page, it was always the callback handling that was painful.
